export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const USER_FETCH_PROFILE = 'USER_FETCH_PROFILE';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';

export const SERVICES_FETCH = 'SERVICES_FETCH';
export const SERVICES_ADD = 'SERVICES_ADD';
export const SERVICES_UPDATE = 'SERVICES_UPDATE';
export const SERVICES_DELETE = 'SERVICES_DELETE';
export const SERVICES_LOADING = 'SERVICES_LOADING';

export const ORDERS_FETCH = 'ORDERS_FETCH';
export const ORDERS_CREATE = 'ORDERS_CREATE';

export const CHAT_SEND = 'CHAT_SEND';
export const CHAT_HISTORY = 'CHAT_HISTORY';

export const SUBSCRIPTIONS_FETCH_TIERS = 'SUBSCRIPTIONS_FETCH_TIERS';
export const SUBSCRIPTIONS_FETCH_MY = 'SUBSCRIPTIONS_FETCH_MY';
export const SUBSCRIPTIONS_CREATE = 'SUBSCRIPTIONS_CREATE';
export const SUBSCRIPTIONS_FETCH_LIST = 'SUBSCRIPTIONS_FETCH_LIST';

export const SELLERS_FETCH_APPLICATIONS = 'SELLERS_FETCH_APPLICATIONS';
export const SELLERS_APPROVE_APPLICATION = 'SELLERS_APPROVE_APPLICATION';
export const SELLERS_DECLINE_APPLICATION = 'SELLERS_DECLINE_APPLICATION';

export const ADMIN_FETCH_USERS = 'ADMIN_FETCH_USERS';
export const ADMIN_EDIT_USER = 'ADMIN_EDIT_USER';
export const ADMIN_DELETE_USER = 'ADMIN_DELETE_USER';
